### ISSUE TITLE
broken - Not working for messages starting with 'Re:' or 'Fwd:'

### ISSUE THREAD

**Issue by ubartram** [mcrispino/gmail-issues#4]
Se rompió ese arreglo. Con al versión actual, está mandando el RE y el Fwd al search del issues y no lo encuentra

**Comment by mcrispino** [comment]
A mi me funciona... ¿Tenés algún ejemplo que no te funcione?

**Comment by ubartram** [comment]
status:closed  ;)

probé de nuevo y me anduvo
